package: petsc

platform:
  - linux-64
  - osx-64

engine:
  - python=2.7
  
iotimeout: 300

before_script:
  - echo "Start building!"

script:
  - conda build . 
  
build-targets: 
  - /opt/miniconda/conda-bld/linux-64/petsc-3.5.2-py27_1.tar.bz2
